# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BIG DATA and CLOUD COMPUTING
email: fmandizvidza@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a Big Data and Cloud Computing enthusiaist.
  HADOOP , AWS (Amazon Web Services) , Microsoft AZURE are my current interests.
  Currently studying for Certifications in those Technologies.
  I have over 25 years of experience in the Information Technology Landscape.
  System Design/Development (Financial Solutions and some Web Based applications), Project Leadership (PRINCE2 ,CAPM) , ITIL Foundation.
  I enjoy learning and reading about latest Techonological Advancements.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.bidacloco.com" # the base hostname & protocol for your site
twitter_username: fungimandi
github_username:  fmandi

# Build settings
markdown: kramdown
